import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Navbar/page";
import InhabitrSignup from "@/components/InhabitrSignup/InhabitrSignup";
import { sessionStatus } from "@/utils/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {sessionStatus ? <Header/> : ''}
        {children}
        </body>
    </html>
  );
}
