// import React from 'react'

// const Login = () => {
//   return (
//     <div className='bg-[#F1F1F1] p-0 w-full h-screen flex justify-end items-center'>
//         <img src='' alt='' />

//         <div className='bg-white flex w-1/2 h-2/3 p-8 m-24'>

//         </div>
//     </div>
//   )
// }

// export default Login

/**
 * This code was generated by Builder.io.
 */
import React from "react";
import LoginForm from "../../components/Form/LoginForm";
import Link from "next/link";
import loginBanner from "../../assets/loginBanner.png"
import Logo from "@/components/Logo/page";

const loginContent = {
    heading: "Welcome!",
    subheading: "Please Log-in to get started!",
    formFooterText: " Not a customer yet?",
    formFooterLink: "Get started!"
}

const Login: React.FC = () => {
  return (
    <main className="overflow-hidden px-16 pt-14 pb-24 bg-[#F1F1F1] max-md:px-5 h-screen justify-center items-center flex font-libre">
      <div className="flex gap-16 max-md:flex-col w-[90%]">
        <section className="flex flex-col w-[56%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col max-md:mt-10 max-md:max-w-full">
            <Logo />
            <img
              loading="lazy"
              src={loginBanner.src}
              alt=""
              className="object-fill self-end mt-4 max-w-full aspect-[1.41] max-md:mt-10 w-full h-full"
            />
          </div>
        </section>
        <section className="flex flex-col w-[44%] ml-5 max-md:ml-0 max-md:w-full">
          <div className="flex  gap-8 overflow-hidden flex-col grow items-center justify-center px-14 pt-16 pb-9 mt-7 w-full bg-white max-md:px-5 max-md:mt-10 max-md:max-w-full">
            <div className="flex flex-col gap-4">
            <h1 className="ml-3 text-4xl font-semibold text-center text-black flex justify-center items-center">
              {loginContent.heading}
            </h1>
            <p className="text-lg font-medium leading-5 text-center text-black">
              {loginContent.subheading}
            </p>
            </div>
            
            <div>
            <LoginForm />
            {/* <SignupForm />
            <ImageUpload /> */}
           
            <p className="mt-7 text-base font-medium leading-5 text-[#837a7a] flex items-center justify-center">
              {loginContent.formFooterText} <span className="text-yellow-600">  <Link href='/register'>&nbsp;
              {loginContent.formFooterLink}
        </Link> </span><br />
            </p>
            </div>
          </div>
        </section>
      </div>
    </main>
  );
};

export default Login;
