/**
 * This code was generated by Builder.io.
 */
import React from "react";
import logo from '../../assets/logo.png'

const Logo: React.FC = () => {
  return (
    <header>
      <img
        loading="lazy"
        src={logo.src}
        alt="Inhabitr logo"
        className="object-contain max-w-full aspect-[2.79] w-[151px] bg-transparent "
      />
    </header>
  );
};

export default Logo;
